# alias
# color alias
alias pacman="pacman --color always"

# update and remove orphaned packages
alias update="sudo pacman -Syu && pacman -Qdt | cut -d ' ' -f 1 | xargs -r pacman -Rdds"

# install package
alias install="sudo pacman -Sy"

# remove package
alias remove="sudo pacman -R"

# remove (with dependencies)
alias remove-clean="sudo pacman -Rnsu"

# search for package (local)
alias search-local="pacman -Qs"

# search for package (remote)
alias search-remote="sudo pacman -Ss"
