# =======================
# ~/.xinitrc
# =======================

# export the preferred terminal (for sxhkd)
export TERMINAL="st"

# start the bar program (which updates xsetroot)
$HOME/github/config/scripts/bar.bash &

# start sxhkd for keybinds
sxhkd &

# using setxkbmap to change keyboard layouts with windows key + space
setxkbmap -layout gb,bg -option grp:win_space_toggle

# start the moving background (looped mpv video playing behind everything)
feh --bg-scale $HOME/pictures/wallpapers/wallpaper

# audio
gentoo-pipewire-launcher&

# finally start dwm
dbus-launch --exit-with-session dwm
